#include "sprites/tree_sprite.h"
#include "sprites/sprite_utils.h"

namespace {
constexpr auto rows = std::array<std::string_view, TREE_HEIGHT>{
    "...............gggg...............",
    "..............ggGGgg..............",
    ".............ggGGGGgg.............",
    "............ggGGGGGGgg............",
    "...........ggGGGGGGGGgg...........",
    "..........ggGGGGGGGGGGgg..........",
    ".........ggGGGGGGGGGGGGgg.........",
    "........ggGGGGGGGGGGGGGGgg........",
    ".......ggGGGGGGGGGGGGGGGGgg.......",
    "......ggGGGGGGGGGGGGGGGGGGgg......",
    ".....ggGGGGGGGGGGGGGGGGGGGGgg.....",
    "....ggGGGGGGGGGGGGGGGGGGGGGGgg....",
    "...ggGGGGGGGGGGGGGGGGGGGGGGGGgg...",
    "..ggGGGGGGGGGGGGGGGGGGGGGGGGGGgg..",
    "..ggGGGGGGGGGGGGGGGGGGGGGGGGGGgg..",
    "..ggGGGGGGGGGGGGGGGGGGGGGGGGGGgg..",
    "..ggGGGGGGGGGGGGGGGGGGGGGGGGGGgg..",
    "..ggGGGGGGGGGGGGGGGGGGGGGGGGGGgg..",
    "...ggGGGGGGGGGGGGGGGGGGGGGGGGgg...",
    "...ggGGGGGGGGGGGGGGGGGGGGGGGGgg...",
    "....ggGGGGGGGGGGGGGGGGGGGGGGgg....",
    ".....ggGGGGGGGGGGGGGGGGGGGGgg.....",
    "......ggGGGGGGGGGGGGGGGGGGgg......",
    ".......ggGGGGGGGGGGGGGGGGgg.......",
    "........ggGGGGGGGGGGGGGGgg........",
    ".........ggGGGGGGGGGGGGgg.........",
    "..........ggGGGGGGGGGGgg..........",
    "...........ggGGGGGGGGgg...........",
    "............ggGGGGGGgg............",
    ".............ggGGGGgg.............",
    "..............ggGGgg..............",
    "...............gggg...............",
    "...............gggg...............",
    "..............ggGGgg..............",
    ".............ggGGGGgg.............",
    "............ggGGGGGGgg............",
    "...........ggGGGGGGGGgg...........",
    "..........ggGGGGGGGGGGgg..........",
    ".........ggGGGGGGGGGGGGgg.........",
    "........ggGGGGGGGGGGGGGGgg........",
    ".......ggGGGGGGGGGGGGGGGGgg.......",
    "......ggGGGGGGGGGGGGGGGGGGgg......",
    ".....ggGGGGGGGGGGGGGGGGGGGGgg.....",
    "....ggGGGGGGGGGGGGGGGGGGGGGGgg....",
    "...ggGGGGGGGGGGGGGGGGGGGGGGGGgg...",
    "..ggGGGGGGGGGGGGGGGGGGGGGGGGGGgg..",
    "..ggGGGGGGGGGGGGGGGGGGGGGGGGGGgg..",
    "...ggGGGGGGGGGGGGGGGGGGGGGGGGgg...",
    "....ggGGGGGGGGGGGGGGGGGGGGGGgg....",
    ".....ggGGGGGGGGGGGGGGGGGGGGgg.....",
    "......ggGGGGGGGGGGGGGGGGGGgg......",
    ".......ggGGGGGGGGGGGGGGGGgg.......",
    "........ggGGGGGGGGGGGGGGgg........",
    ".........ggGGGGGGGGGGGGgg.........",
    "..........ggGGGGGGGGGGgg..........",
    "...........ggGGGGGGGGgg...........",
    "............ggGGGGGGgg............",
    ".............ggGGGGgg.............",
    "..............ggGGgg..............",
    "...............gggg...............",
    "...............gggg...............",
    "...............TTTT...............",
    "...............TTTT...............",
    "...............TTTT...............",
    "...............TTTT...............",
    "...............TTTT...............",
    "...............TTTT...............",
    "...............TTTT...............",
    "...............TTTT...............",
    "...............TTTT...............",
    "...............TTTT...............",
    "...............TTTT...............",
    "...............TTTT...............",
    "...............TTTT...............",
    "...............TTTT...............",
    "...............TTTT...............",
    "...............TTTT...............",
    "...............TTTT...............",
    "...............TTTT...............",
    "...............TTTT...............",
    "...............TTTT..............."};

constexpr auto palette = std::array{
    std::pair{'g', rgba(30, 120, 50)},
    std::pair{'G', rgba(70, 180, 90)},
    std::pair{'T', rgba(120, 80, 30)},
};
} // namespace

const std::array<Uint32, TREE_WIDTH * TREE_HEIGHT> TREE_PIXELS =
    makeSpriteFromArt<TREE_WIDTH, TREE_HEIGHT, palette.size()>(rows, palette);
